# 04 - 01 Multiple Input

<img width="200" src="https://i.imgur.com/hbPVe1T.png">

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
%%writefile "data-01-test-score.csv"
73,80,75,152
93,88,93,185
89,91,90,180
96,98,100,196
73,66,70,142
53,46,55,101
69,74,77,149
47,56,60,115
87,79,90,175
79,70,88,164
69,70,73,141
70,65,74,141
93,95,91,184
79,80,73,152
70,73,78,148
93,89,96,192
78,75,68,147
81,90,93,183
88,92,86,177
78,83,77,159
82,86,90,177
86,82,89,175
78,83,85,175
76,83,71,149
96,93,95,192

Overwriting data-01-test-score.csv


In [3]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',')
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print("x_data", x_data)
print("y_data", y_data)

x_data [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
y_data [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(input_dim=3, units=1))

model.compile(loss='mse', optimizer='rmsprop')
model.fit(x_data, y_data, epochs=2000, verbose=0)

In [5]:
model.predict(np.array([[0, 2, 1]]))

array([[2.7772412]], dtype=float32)

In [6]:
model.predict(np.array([[0, 9, -1]]))

array([[5.0239377]], dtype=float32)

In [7]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import RMSprop
import numpy as np

x_data = np.array(
   [[73., 80., 75.],
    [93., 88., 93.],
    [89., 91., 90.],
    [96., 98., 100.],
    [73., 66., 70.]]
)

y_data = np.array(
    [152.,185., 180., 196., 142.]
)

model = Sequential()
model.add(Dense(input_dim=3, units=1))
model.add(Activation('linear'))

rmsprop = RMSprop(lr=1e-10)
model.compile(loss='mse', optimizer=rmsprop)
model.fit(x_data, y_data, epochs=1000, verbose=0)

y_predict = model.predict(np.array([[95., 100., 80]]))
print(y_predict)

Using TensorFlow backend.


[[-186.60214]]


In [8]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

x_data = np.array(
   [[73., 80., 75.],
    [93., 88., 93.],
    [89., 91., 90.],
    [96., 98., 100.],
    [73., 66., 70.]]
)

y_data = np.array(
    [152.,185., 180., 196., 142.]
)

model = Sequential()
model.add(Dense(input_dim=3, units=1))

model.compile(loss='mse', optimizer='rmsprop')
model.fit(x_data, y_data,epochs=1000,verbose=0)

In [9]:
y_predict = model.predict(np.array([[96., 98., 99]]))
print(y_predict)

[[193.99263]]
